version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx:main
    depends_on: [orthanc, orthanc-auth-service, orthanc-for-api, meddream-viewer, keycloak]
    restart: unless-stopped
    ports: ["80:80"]
# if setting ENABLE_HTTPS: "true" env var, uncomment the following 4 lines and comment the line with 'ports: ["80:80"]'
# Build the nginx configuration for ssl on 192.168.xxxxxx.xxxx
# include the absolute directory path for the ssl configuration on the volumes path 
#   ports: ["443:443"]
#  volumes:
# NOTE!!!!!! change the directory path listed here
# BUILD A NEW SSL WITH THIS CONFIGURATION OPTIONS
# 1. sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /home/path to custom keys/finalsetup/sslkeys/private.key -out /home/holyfire/finalsetup/sslkeys/certificate.crt
# 2. cat /home/path to ssl keys/finalsetup/sslkeys/private.key /home/path to custom/finalsetup/sslkeys/certificate.crt > /home/holyfire/finalsetup/sslkeys/crt.pem
# 3. sudo cp private.key ./key.pem

#    - /path/to/custom/crt.pem:/etc/nginx/tls/crt.pem
#    - /path/to/custom/key.pem:/etc/nginx/tls/key.pem
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_OHIF: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "true"
# changed the HTTPS to be TRUE  !!!!
      ENABLE_HTTPS: "false"
      ENABLE_MEDDREAM: "true"
      ENABLE_WSI: "true"
      ENABLE_ORTHANC_FOR_API: "true"

  orthanc:
      # image is already built with the custom oe2 options 
    image: orthancteam/orthanc:24.3.5-full
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      # Please change mount path before running docker-compose
      - /path/to/custom/custom.css:/home/custom/custom.css
      - /path/to/custom/logo.png:/home/custom/logo.png

    depends_on: [orthanc-db]
    ports: ["4242:4242", "8042:8042"]
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      HOUSEKEEPER_PLUGIN_ENABLED: "true"
      DELAYED_DELETION_PLUGIN_ENABLED: "true"
      NEURO_PLUGIN_ENABLED: "true"
      WSI_PLUGIN_ENABLED: "true"
      CONNECTIVITY_CHECKS_PLUGIN_ENABLED: "true"
      WORKLISTS_PLUGIN_ENABLED: "true"
      TCIA_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER_PLUGIN_ENABLED: "false"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 10
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_SHARES: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__SHOW_SAME_PATIENT_STUDIES_FILTER: '["PatientBirthDate"]'
      ORTHANC_JSON: |
        {
          "Name": "MAIN SERVER 1",
          "StorageCompression" : true,
          "MaximumStorageSize" : 0,
          "MaximumPatientCount" : 0,
          "MaximumStorageCacheSize" : 128,
          "MaximumStorageMode" : "Recycle",
          "HttpServerEnabled" : true,
          "HttpPort" : 8042,
          "LuaHeartBeatPeriod" : 0,
          "LuaScripts" : [ "/etc/share/orthanc/scripts/sendtopeer.lua"
          ],
          "ConcurrentJobs" : 7,
          "JobsEngineThreadsCount" : {
            "ResourceModification": 1
          },
          "WebDavEnabled" : true,
          "WebDavDeleteAllowed" : false,
          "WebDavUploadAllowed" : true,
          "DicomServerEnabled" : true,
          "DicomAet" : "SERVERMAIN1",
          "DicomCheckCalledAet" : true,
          "DicomPort" : 4242,
          "DefaultEncoding" : "Latin1",
          "AcceptedTransferSyntaxes" : [ "1.2.840.10008.1.*" ],
          "UnknownSopClassAccepted" : false,
          "DicomScpTimeout" : 30,
          "SslEnabled" : false,
          "SslCertificate" : "certificate.pem",
          "SslMinimumProtocolVersion" : 4,
          "SslVerifyPeers" : false,
          "SslTrustedClientCertificates" : "trustedClientCertificates.pem",
          "DicomTlsEnabled" : false,
          "DicomTlsRemoteCertificateRequired" : true,
          "DicomAlwaysAllowEcho" : true,
          "DicomAlwaysAllowStore" : true,
          "DicomAlwaysAllowFind" : true,
          "DicomAlwaysAllowFindWorklist" : true,
          "DicomAlwaysAllowGet" : true,
          "DicomAlwaysAllowMove" : true,
          "DicomCheckModalityHost" : false,
          "DicomModalities" : {
            "MRI" : [ "MICRODICOM", "192.168.43.128", 11119],
            "CT-1" : [ "RADIANT", "192.168.43.128", 11112],
            "CT-2" : [ "fac1", "192.168.0.184", 11116],
            "Dental-x-ray" : [ "DENTALMAIN", "192.168.43.9", 104],
            "Eye-fundus-Camera" : [ "xxxx", "192.168.0.184", 11118],
            "Eye-OCT" : [ "fxxxxx4", "192.168.0.184", 11119],
            "Echo-machine-1" : [ "xxxx", "192.168.0.194", 11110],
            "Echo-machine-2" : [ "xxxx", "192.168.0.194", 1100],
            "ECG-Machine" : [ "xxxx", "192.168.0.64", 11111],
            "Endoscopy-machine" : [ "fmcac7", "192.168.0.140", 11112],
            "Mamography" : [ "xxxx", "192.168.0.133", 11113],
            "US-1" : [ "xxxx", "192.168.0.187", 1114],
            "US-2" : [ "xxxxx", "192.168.0.14", 2222],
            "US-3" : [ "xxxxx", "192.168.0.200", 1826],
            "x-ray" : [ "xxxx", "192.168.43.10", 2323],
            "Fluoroscopy" : [ "xxxx", "192.168.43.190", 2424]
          },
          "DicomModalitiesInDatabase" : false,
          "DicomEchoChecksFind" : false,
          "DicomScuTimeout" : 10,
          "DicomScuPreferredTransferSyntax" : "1.2.840.10008.1.2.1",
          "DicomThreadsCount" : 4,
          "OrthancPeers" : {
            "CLOUD_SERVER" : [ "https://www.mydomain.com/" ],
            "PUBLIC_SERVER" : [ "http://192.168.43.195:8042/" ]
          },
          "OrthancPeersInDatabase" : false,
          "HttpProxy" : "",
          "HttpVerbose" : false,
          "HttpTimeout" : 60,
          "HttpsVerifyPeers" : true,
          "HttpsCACertificates" : "/etc/ssl/certs/ca-certificates.crt",
          "UserMetadata" : {
            // "Sample" : 1024
          },
          "UserContentType" : {
            // "sample" : 1024
            // "sample2" : [ 1025, "application/pdf" ]
          },
          "StableAge" : 60,
          "StrictAetComparison" : false,
          "StoreMD5ForAttachments" : true,
          "LimitFindResults" : 0,
          "LimitFindInstances" : 0,
          "LogExportedResources" : false,
          "KeepAlive" : true,
          "TcpNoDelay" : true,
          "HttpThreadsCount" : 50,
          "StoreDicom" : true,
          "DicomAssociationCloseDelay" : 5,
          "QueryRetrieveSize" : 100,
          "CaseSensitivePN" : false,
          "LoadPrivateDictionary" : true,
          "Dictionary" : {
          },
          "SynchronousCMove" : true,
          "JobsHistorySize" : 10,
          "SaveJobs" : true,
          "OverwriteInstances" : false,
          "MediaArchiveSize" : 1,
          "StorageAccessOnFind" : "Always",
          "MetricsEnabled" : true,
          "ExecuteLuaEnabled" : false,
          "HttpRequestTimeout" : 30,
          "DefaultPrivateCreator" : "",
          "StorageCommitmentReportsSize" : 100,
          "TranscodeDicomProtocol" : true,
          "BuiltinDecoderTranscoderOrder" : "After",
          "IngestTranscoding" : "1.2.840.10008.1.2.4.91",
          "IngestTranscodingOfUncompressed" : true,
          "IngestTranscodingOfCompressed" : true,
          "DicomLossyTranscodingQuality" : 90,
          "SyncStorageArea" : true,
          "MallocArenaMax" : 5,
          "DeidentifyLogs" : true,
          "DeidentifyLogsDicomVersion" : "2021b",
          "MaximumPduLength" : 16384,
          "CheckRevisions" : false,
          "SynchronousZipStream" : true,
          "ZipLoaderThreads": 0,
          "Warnings" : {
            "W001_TagsBeingReadFromStorage": true,
            "W002_InconsistentDicomTagsInDb": true
          },
          "OrthancExplorer2": {
            "IsDefaultUI": true,
            "Theme": "dark",
            "CustomCssPath": "/home/custom/custom.css",
            "CustomLogoPath": "/home/custom/logo.png",
            "UiOptions": {
              "EnableOpenInMedDreamViewer": true,
              "EnableOpenInOhifViewer3": true,
              "EnableShares": true,
              "ShowOrthancName": true,
              "MaxStudiesDisplayed": 5000,
              "MaxMyJobsHistorySize": 5,
              "EnableDownloadDicomDir": true,
              "EnableDownloadDicomFile": true,
              "DefaultShareDuration": 0,
              "EnableApiViewMenu": true,
              "EnableEditLabels": true,
              "StudyListSearchMode": "search-button",
              "StudyListContentIfNoSearch": "empty",
              "ShareDurations": [0, 7, 15, 30, 90, 365],
              "EnableOpenInOhifViewer3": true,
              "OhifViewer3PublicRoot": "http://localhost/ohif/",
              "ViewersIcons" : {
                "osimis-web-viewer": "bi bi-eye",
                "stone-webviewer": "bi bi-eye-fill",
                "ohif": "bi bi-grid",
                "ohif-vr": "bi bi-grid-1x2",
                "ohif-tmtv": "bi bi-grid-3x3-gap",
                "ohif-seg": "fa-solid fa-shapes fa-button",
                "ohif-micro": "fa-solid fa-microscope fa-button",
                "meddream": "bi bi-columns-gap",
                "volview": "bi bi-box",
                "wsi": "fa-solid fa-microscope fa-button"
              },
              "ViewersOrdering" : [
                "osimis-web-viewer",
                "stone-webviewer",
                "ohif",
                "ohif-vr",
                "ohif-tmtv",
                "ohif-seg",
                "ohif-micro",
                "meddream",
                "volview",
                "wsi"
              ],
              "StudyMainTags" : [
                "StudyDate",
                "StudyTime",
                "StudyDescription",
                "AccessionNumber",
                "StudyID",
                "StudyInstanceUID",
                "RequestingPhysician",
                "ReferringPhysicianName",
                "Department",
                "ReportingDoctor",
                "InstitutionName"
              ],
              "SeriesMainTags" : [
                "SeriesDate",
                "SeriesTime",
                "SeriesDescription",
                "SeriesNumber",
                "BodyPartExamined",
                "ProtocolName",
                "SeriesInstanceUID"
              ],
              "StudyListColumns" : [
                "PatientBirthDate",
                "PatientName",
                "PatientID",
                "StudyDescription",
                "StudyDate",
                "modalities",
                "AccNumber",
                "seriesCount"
              ]
            },
            "Tokens" : {
              "InstantLinksValidity": 3600,
              "ShareType": "ohif-viewer-publication"
            },
            "Keycloak" : {
              "Enable": true,
              "Url": "http://localhost/keycloak/",
              "Realm": "orthanc",
              "ClientId": "orthanc"
            }
          },
          "AuthenticationEnabled": false,     // because it is handled by the authorization plugin
          "Authorization": {
            "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
            "WebServiceUsername": "share-user",
            "WebServicePassword": "change-me",
            "StandardConfigurations" : [
              "osimis-web-viewer",
              "stone-webviewer",
              "orthanc-explorer-2"
            ],
            "CheckedLevel": "studies"
          },
          "DicomWeb": {
            "Enable": true,
            "PublicRoot": "/orthanc/dicom-web/"
          },
          "Housekeeper": {
            "Enable": true,
            "GlobalPropertyId": 1025,
            "Force": false,
            "ThrottleDelay": 5,
            "Schedule": {
              "Monday": ["2-4"],
              "Tuesday": ["2-4"],
              "Wednesday": ["2-4"],
              "Thursday": ["3-5"],
              "Friday": ["3-5"],
              "Saturday": ["22-24"],
              "Sunday": ["22-24"]
            },
            "Triggers" : {
              "StorageCompressionChange": true,
              "MainDicomTagsChange": true,
              "UnnecessaryDicomAsJsonFiles": true
            }
          },
          "WholeSlideImaging" : {
            "EnableIIIF" : true,
            "OrthancPublicURL" : "http://localhost/orthanc/ui/app",
            "ServeMirador" : true,
            "ServeOpenSeadragon" : true,
            "ForcePowersOfTwoScaleFactors" : true
          },
          "Tcia" : {
            "Enable" : true
          }
        }

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:main
    depends_on: [keycloak, meddream-token-service]
    # permissions can be customized in the permissions.json file
    volumes:
      - ./permissions.jsonc:/orthanc_auth_service/permissions.json
    restart: unless-stopped
    environment:
      SECRET_KEY: "change-me-I-am-a-secret-key"
      ENABLE_KEYCLOAK: "true"
      PUBLIC_ORTHANC_ROOT: "http://localhost/orthanc/"
      PUBLIC_LANDING_ROOT: "http://localhost/orthanc/ui/app/token-landing.html"
      USERS: |
        {
          "share-user": "change-me"
        }
      MEDDREAM_TOKEN_SERVICE_URL: "http://meddream-token-service:8088/v3/generate"
      PUBLIC_MEDDREAM_ROOT: "http://localhost/meddream/"
      PUBLIC_OHIF_ROOT: "http://localhost/ohif/"

  orthanc-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  keycloak:
    image: orthancteam/orthanc-keycloak:main
    depends_on: [keycloak-db]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "change-me"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME_URL: "http://localhost/keycloak"
      KC_HOSTNAME_ADMIN_URL: "http://localhost/keycloak"

  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

  meddream-token-service:
    image: orthancteam/meddream-token-service:main
    restart: unless-stopped

  ohif:
    image: orthancteam/ohif-v3:main
#  customize ohif configuration applied
    volumes:
      - ./ohif.js:/usr/share/nginx/html/app-config.js
      - ./ohif-logo.svg:/usr/share/nginx/html/ohif-logo.svg:ro
#      - ./ohif-logo-light.svg:/usr/share/nginx/html/ohif-logo-light.svg:ro
    restart: unless-stopped

  meddream-viewer:
    image: orthancteam/meddream-viewer:main
    restart: unless-stopped
    depends_on:
      - orthanc-for-api
    environment:
      integration: "study"
      TOKEN_SERVICE_ADDRESS: "http://meddream-token-service:8088/v3/validate"
      ORTHANC_BASE_URL: "http://orthanc-for-api:8042"
      ORTHANC_USER: "meddream-user"
      ORTHANC_PWD: "change-me"
      ORTHANC_MEDDREAM_PYTHON_PLUGIN_ENABLED: "true"
      MEDDREAM_ADMIN_PASSWORD: "change-me"
      MEDDREAM_PACS_CONFIG_TYPE: "Dicomweb"
      ORTHANC_HOSTNAME: "orthanc-for-api"
      ORTHANC_DICOM_PORT: 4242
      ORTHANC_AET: "SERVERMAIN1"
    volumes:
      - meddream-license:/opt/meddream/license

  # An orthanc dedicated for API accesses and also used by MedDream
  orthanc-for-api:
    image: orthancteam/orthanc:24.3.5-full
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./meddream-plugin.py:/scripts/meddream-plugin.py
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for API"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/scripts/meddream-plugin.py"
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc-api/dicom-web/"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC_JSON: |
        {
          "RegisteredUsers": {
            "meddream-user": "change-me",
            "script-user": "change-me",
            "dicom-web-client-user": "change-me"
          }
        }


volumes:
  orthanc-storage:
  orthanc-db:
  keycloak-db:
  meddream-license:
